# Generated by Django 5.2.5 on 2025-09-11 11:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('shops', '0002_alter_shop_options_shop_is_active_shop_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Optional service description', validators=[core.validators.validate_safe_string]),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Service is currently offered'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text="Service name (e.g., 'Dry Clean', 'Wash & Fold')", max_length=100, validators=[core.validators.validate_safe_string, core.validators.validate_no_special_chars]),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['shop', 'name'], name='services_se_shop_id_ac8d58_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'),
        ),
    ]
