# Generated by Django 5.2.5 on 2025-09-11 11:46

import core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Shop is currently active'),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(help_text='Shop address', validators=[core.validators.validate_safe_string]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='Shop name (alphanumeric characters, spaces, hyphens, periods only)', max_length=255, validators=[core.validators.validate_safe_string, core.validators.validate_no_special_chars]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=20, validators=[core.validators.validate_phone_number]),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['name'], name='shops_shop_name_da338f_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active'], name='shops_shop_is_acti_bbb154_idx'),
        ),
    ]
