# Generated by Django 5.2.5 on 2025-09-11 17:12

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_options_shop_is_active_shop_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Job position/title', max_length=100, validators=[core.validators.validate_safe_string])),
                ('is_active', models.BooleanField(default=True, help_text='Staff member is currently active')),
                ('can_take_orders', models.BooleanField(default=True, help_text='Can create and manage orders')),
                ('can_update_orders', models.BooleanField(default=True, help_text='Can update order status')),
                ('can_register_customers', models.BooleanField(default=True, help_text='Can register new customers')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly wage rate', max_digits=8, null=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the staff member', validators=[core.validators.validate_safe_string])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='shops.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Staff Member',
                'verbose_name_plural': 'Shop Staff Members',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'is_active'], name='shops_shops_shop_id_7e6dad_idx'), models.Index(fields=['user'], name='shops_shops_user_id_4bc0e6_idx')],
            },
        ),
    ]
