# Generated by Django 5.2.5 on 2025-09-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('services', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.service'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceprice',
            unique_together={('shop', 'service', 'item')},
        ),
    ]
