# Generated by Django 5.2.5 on 2025-09-11 11:46

import core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
        ('services', '0002_alter_service_options_service_description_and_more'),
        ('shops', '0002_alter_shop_options_shop_is_active_shop_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'ordering': ['service__name', 'item__name']},
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Optional item description', validators=[core.validators.validate_safe_string]),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Item is currently accepted'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Price is currently active'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text="Item name (e.g., 'Shirt', 'Dress', 'Suit')", max_length=100, validators=[core.validators.validate_safe_string, core.validators.validate_no_special_chars]),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for this service-item combination', max_digits=8, validators=[core.validators.validate_price]),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['shop', 'name'], name='items_item_shop_id_cc208c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='items_item_is_acti_391f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['shop', 'service', 'item'], name='items_servi_shop_id_f92c05_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['is_active'], name='items_servi_is_acti_eb1fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['price'], name='items_servi_price_a1df1b_idx'),
        ),
    ]
